### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by youngqqcn** [orientwalt/htdf#18]
```
time="2020-12-24T19:05:31+08:00" level=info msg="curLastIndex: 4388285"
I[2020-12-24|19:05:31.157] Executed block                               module=state height=4388636 validTxs=0 invalidTxs=0
I[2020-12-24|19:05:31.172] Committed state                              module=state height=4388636 txs=0 appHash=C5F580DB8A1E38AA8D6C933D04578DFED439F0FB6CF840B03810C221E273E57A
E[2020-12-24|19:05:32.113] Connection failed @ sendRoutine              module=p2p peer=06003cba9c1681b1452d6a241593b7baf5ec08d8@47.74.190.240:43003 conn=MConn{47.74.190.240:43003} err="pong timeout"
E[2020-12-24|19:05:32.113] Stopping peer for error                      module=p2p peer="Peer{MConn{47.74.190.240:43003} 06003cba9c1681b1452d6a241593b7baf5ec08d8 in}" err="pong timeout"
panic: open /root/.hsd/data/cs.wal: too many open files

goroutine 139808 [running]:
github.com/tendermint/tendermint/libs/autofile.(*Group).readGroupInfo(0xc00c208790, 0x0, 0x0, 0x0, 0x0)
  /media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/projects/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/libs/autofile/group.go:359 +0x547
github.com/tendermint/tendermint/libs/autofile.(*Group).checkTotalSizeLimit(0xc00c208790)
  /media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/projects/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/libs/autofile/group.go:268 +0x64
github.com/tendermint/tendermint/libs/autofile.(*Group).processTicks(0xc00c208790)
  /media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/projects/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/libs/autofile/group.go:239 +0x91
created by github.com/tendermint/tendermint/libs/autofile.(*Group).OnStart
  /media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/projects/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/libs/autofile/group.go:138 +0x66
```

**Comment by youngqqcn** [comment]
check system limit configuration by `ulimit -n` ,   this value should be set larger than `1024`.   `65535` is recommended.
