### ISSUE TITLE
hsd(Block.AppHash!= State.AppHash) compatibility problem

### ISSUE THREAD

**Issue by bluesky0125** [orientwalt/htdf#2]
when hsd's apphash is not same with distributions', sync failed.
```
$hsd version
GitCommit=569c44b|version=1.1.0|GitBranch=release|
$ hsd start
...
INFO[0101] totalSupply 6000000459394710                 
INFO[0101] curBlkHeight: 1                              
INFO[0101] curBlkHeight: 1                              
INFO[0101] BlockProvision: 14467592                     
INFO[0101] curAmplitude: 0                              
INFO[0101] curCycle: 1                                  
INFO[0101] curLastIndex: 1                              
I[2020-03-24|02:22:44.963] Executed block                               module=state height=1 validTxs=0 invalidTxs=0
I[2020-03-24|02:22:51.676] Committed state                              module=state height=1 txs=0 appHash=8C92EBCB85B4DA83D764DB0BB88F5BEB5FCC86129F7D2E332E97E600C406C2AC
panic: Failed to process committed block (2:FC33AFC1A57F0A05F22EF2F38E3060CE7386EE81CE96D7680E5B592018C4031C): Wrong Block.Header.AppHash.  Expected 8C92EBCB85B4DA83D764DB0BB88F5BEB5FCC86129F7D2E332E97E600C406C2AC, got 9F87C079D6297038C0E7C2A0C869A7BD50AB042B5DDEB84584944BE8C54CB207

goroutine 126 [running]:
github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc000af49c0)
        /home/xxx/go/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/blockchain/reactor.go:347 +0x1578
created by github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
        /home/xxx/go/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/blockchain/reactor.go:117 +0x84

**Comment by bluesky0125** [comment]
htdf includes some modules which could affect StateDB, such as msg, codec, route. If you add some api querying variables after writing them into StateDB, it will definitely cause this issue. so, when you have to upgrade application but still need to be compatible with the chain, you should be clear what could be upgrade and what could be not.

you can change or add the followings.

you must keep the following modules.
