### ISSUE TITLE
test new feature of replay-last-block

### ISSUE THREAD

**Issue by youngqqcn** [orientwalt/htdf#21]
If a  validator node  proposed a invalid block , we could use the right version `hsd` and `hsd --replay-last-block` to replay the last block. If occurs errors like `err="error signing vote: round regression at height 13853. Got 1, last round 9"`  , don't worry just wait for  it recovering.

**Comment by youngqqcn** [comment]
2nd test result:


```
C[root@node4 ~]# hsd start
I[2021-01-05|14:20:53.498] Starting ABCI with Tendermint                module=main 
INFO[0000] /---------flag1----------/ true              
currVersion=2
LastBlockHeight=14166
INFO[0001] totalSupply 400000000000000000               
INFO[0001] curBlkHeight: 14167                          
I[2021-01-05|14:20:55.193] Executed block                               module=state height=14167 validTxs=0 invalidTxs=0
I[2021-01-05|14:20:55.205] Committed state                              module=state height=14167 txs=0 appHash=FE6E580E1B36AC6E38C0B93D4BD72939F54BB4A28B2BC29E4A901636AD980F5F
E[2021-01-05|14:20:56.598] Error dialing peer                           module=p2p err="auth failure: secret conn failed: EOF"
INFO[0006] totalSupply 400000000000000000               
INFO[0006] curBlkHeight: 14168                          
I[2021-01-05|14:21:00.397] Executed block                               module=state height=14168 validTxs=0 invalidTxs=0
I[2021-01-05|14:21:00.402] Committed state                              module=state height=14168 txs=0 appHash=0D5DDA184E4051E94D59B7BAE53D3FE5367922FE12EB5F94B724735EEC8A498C
INFO[0012] totalSupply 400000000000000000               
INFO[0012] curBlkHeight: 14169                          
I[2021-01-05|14:21:05.802] Executed block                               module=state height=14169 validTxs=0 invalidTxs=0
I[2021-01-05|14:21:05.808] Committed state                              module=state height=14169 txs=0 appHash=4C95EC7E7CEC360A231BA6918E86638AD7ED733AF1D96378DC828EFE924AF37B
INFO[0017] totalSupply 400000000000000000               
INFO[0017] curBlkHeight: 14170                          
INFO[0017] blockHeaderTime: 2021-01-05T06:21:05.691711305Z 
I[2021-01-05|14:21:11.019] Executed block                               module=state height=14170 validTxs=1 invalidTxs=0
I[2021-01-05|14:21:11.024] Committed state                              module=state height=14170 txs=1 appHash=878D2C17CE8F38F6D2AAE5DE53977CAE61AC7B58F42C83170AF99859A780A644
INFO[0023] totalSupply 400000000000000000               
INFO[0023] curBlkHeight: 14171                          
I[2021-01-05|14:21:16.417] Executed block                               module=state height=14171 validTxs=0 invalidTxs=0
I[2021-01-05|14:21:16.421] Committed state                              module=state height=14171 txs=0 appHash=3D3069C92B6D9793480634F1DFB0D19923D13B9E503888606C3AC0CA07734702
INFO[0028] totalSupply 400000000000000000               
INFO[0028] curBlkHeight: 14172                          
I[2021-01-05|14:21:21.631] Executed block                               module=state height=14172 validTxs=0 invalidTxs=0
I[2021-01-05|14:21:21.636] Committed state                              module=state height=14172 txs=0 appHash=3F9B8DE2CA12B671315132FB05B2D979BB7B1F317ADEE66329DEF76D4F62C41A
E[2021-01-05|14:21:23.670] Dialing failed                               module=pex addr=7292fe1c7dcf921f2176a9a178610dba7d233ac8@192.168.0.174:26656 err="auth failure: secret conn failed: EOF" attempts=0
INFO[0033] totalSupply 400000000000000000               
INFO[0033] curBlkHeight: 14173                          
INFO[0033] === v2.HandleOpenContract  ===               
INFO[0033] blockHeaderTime: 2021-01-05T06:21:21.614824672Z 
WARN[0033] !!!!!!!!!!!HACK_TEST__blockHeaderTime: 2021-01-05T06:31:21.614824672Z !!!!!!!!! 
I[2021-01-05|14:21:27.037] Executed block                               module=state height=14173 validTxs=1 invalidTxs=0
I[2021-01-05|14:21:27.043] Committed state                              module=state height=14173 txs=1 appHash=73630D5AC8B1A266A7B1E35368868CDF4F64D387492CBDCF62CA322EACF002DB
INFO[0038] totalSupply 400000000000000000               
INFO[0038] curBlkHeight: 14174                          
I[2021-01-05|14:21:32.266] Executed block                               module=state height=14174 validTxs=0 invalidTxs=0
I[2021-01-05|14:21:32.271] Committed state                              module=state height=14174 txs=0 appHash=DB7E6C98DAC7E2C448F138561BE8ED1AC0B2DB2C38954C2B3AC9617FE291E71E
INFO[0044] totalSupply 400000000000000000               
INFO[0044] curBlkHeight: 14175                          
INFO[0044] === v2.HandleOpenContract  ===               
INFO[0044] blockHeaderTime: 2021-01-05T06:21:32.249261941Z 
WARN[0044] !!!!!!!!!!!HACK_TEST__blockHeaderTime: 2021-01-05T06:31:32.249261941Z !!!!!!!!! 
I[2021-01-05|14:21:37.654] Executed block                               module=state height=14175 validTxs=1 invalidTxs=0
I[2021-01-05|14:21:37.662] Committed state                              module=state height=14175 txs=1 appHash=A8753B91B2EE3E391EA0DA87E2FB66F591BDC95F1B5AB901F6BEC4BE357F04B9
E[2021-01-05|14:21:45.053] enterPrevote: ProposalBlock is invalid       module=consensus height=14176 round=1 err="Wrong Block.Header.AppHash.  Expected A8753B91B2EE3E391EA0DA87E2FB66F591BDC95F1B5AB901F6BEC4BE357F04B9, got 6007DF17B8E4E8ED5D308220BFB806311EB74C118D26FDD370DEB7DEF3FE29FC"
E[2021-01-05|14:21:52.674] enterPrevote: ProposalBlock is invalid       module=consensus height=14176 round=3 err="Wrong Block.Header.AppHash.  Expected A8753B91B2EE3E391EA0DA87E2FB66F591BDC95F1B5AB901F6BEC4BE357F04B9, got 6007DF17B8E4E8ED5D308220BFB806311EB74C118D26FDD370DEB7DEF3FE29FC"
E[2021-01-05|14:21:53.670] Dialing failed                               module=pex addr=7292fe1c7dcf921f2176a9a178610dba7d233ac8@192.168.0.174:26656 err="auth failure: secret conn failed: EOF" attempts=1
E[2021-01-05|14:22:04.295] enterPrevote: ProposalBlock is invalid       module=consensus height=14176 round=5 err="Wrong Block.Header.AppHash.  Expected A8753B91B2EE3E391EA0DA87E2FB66F591BDC95F1B5AB901F6BEC4BE357F04B9, got 6007DF17B8E4E8ED5D308220BFB806311EB74C118D26FDD370DEB7DEF3FE29FC"
^C[root@node4 ~]# ./hsd start --replay-last-block
I[2021-01-05|14:22:22.885] Starting ABCI with Tendermint                module=main 
I[2021-01-05|14:22:22.918] Blockstore height equals to current state height 14175 module=main 
I[2021-01-05|14:22:22.918] Just reset state DB to last height           module=main 
INFO[0000] /---------flag1----------/ true              
currVersion=2
LastBlockHeight=14174
INFO[0000] totalSupply 400000000000000000               
INFO[0000] curBlkHeight: 14175                          
INFO[0000] === v2.HandleOpenContract  ===               
INFO[0000] blockHeaderTime: 2021-01-05T06:21:32.249261941Z 
E[2021-01-05|14:22:23.075] Dialing failed                               module=pex addr=7292fe1c7dcf921f2176a9a178610dba7d233ac8@192.168.0.174:26656 err="auth failure: secret conn failed: read tcp 192.168.0.174:60756->192.168.0.174:26656: read: connection reset by peer" attempts=0
E[2021-01-05|14:22:23.131] Error dialing peer                           module=p2p err="auth failure: secret conn failed: EOF"
E[2021-01-05|14:22:24.323] enterPrevote: ProposalBlock is invalid       module=consensus height=14176 round=0 err="Wrong Block.Header.AppHash.  Expected 6007DF17B8E4E8ED5D308220BFB806311EB74C118D26FDD370DEB7DEF3FE29FC, got A8753B91B2EE3E391EA0DA87E2FB66F591BDC95F1B5AB901F6BEC4BE357F04B9"
E[2021-01-05|14:22:24.324] Error signing vote                           module=consensus height=14176 round=0 vote="Vote{3:BA9BF4CBA3A4 14176/00/1(Prevote) 000000000000 000000000000 @ 2021-01-05T06:22:24.324291024Z}" err="error signing vote: round regression at height 14176. Got 0, last round 5"
E[2021-01-05|14:22:24.326] Error signing vote                           module=consensus height=14176 round=0 vote="Vote{3:BA9BF4CBA3A4 14176/00/2(Precommit) 000000000000 000000000000 @ 2021-01-05T06:22:24.32603026Z}" err="error signing vote: round regression at height 14176. Got 0, last round 5"
E[2021-01-05|14:22:24.328] Error signing vote                           module=consensus height=14176 round=1 vote="Vote{3:BA9BF4CBA3A4 14176/01/1(Prevote) 6B052D3BFE1F 000000000000 @ 2021-01-05T06:22:24.328620246Z}" err="error signing vote: round regression at height 14176. Got 1, last round 5"
E[2021-01-05|14:22:24.330] Error signing vote                           module=consensus height=14176 round=1 vote="Vote{3:BA9BF4CBA3A4 14176/01/2(Precommit) 000000000000 000000000000 @ 2021-01-05T06:22:24.330055579Z}" err="error signing vote: round regression at height 14176. Got 1, last round 5"
E[2021-01-05|14:22:24.332] enterPrevote: ProposalBlock is invalid       module=consensus height=14176 round=2 err="Wrong Block.Header.AppHash.  Expected 6007DF17B8E4E8ED5D308220BFB806311EB74C118D26FDD370DEB7DEF3FE29FC, got A8753B91B2EE3E391EA0DA87E2FB66F591BDC95F1B5AB901F6BEC4BE357F04B9"
E[2021-01-05|14:22:24.332] Error signing vote                           module=consensus height=14176 round=2 vote="Vote{3:BA9BF4CBA3A4 14176/02/1(Prevote) 000000000000 000000000000 @ 2021-01-05T06:22:24.332356667Z}" err="error signing vote: round regression at height 14176. Got 2, last round 5"
E[2021-01-05|14:22:24.333] Error signing vote                           module=consensus height=14176 round=2 vote="Vote{3:BA9BF4CBA3A4 14176/02/2(Precommit) 000000000000 000000000000 @ 2021-01-05T06:22:24.33387508Z}" err="error signing vote: round regression at height 14176. Got 2, last round 5"
E[2021-01-05|14:22:24.336] Error signing vote                           module=consensus height=14176 round=3 vote="Vote{3:BA9BF4CBA3A4 14176/03/1(Prevote) 6B052D3BFE1F 000000000000 @ 2021-01-05T06:22:24.336717029Z}" err="error signing vote: round regression at height 14176. Got 3, last round 5"
E[2021-01-05|14:22:24.338] Error signing vote                           module=consensus height=14176 round=3 vote="Vote{3:BA9BF4CBA3A4 14176/03/2(Precommit) 000000000000 000000000000 @ 2021-01-05T06:22:24.338136238Z}" err="error signing vote: round regression at height 14176. Got 3, last round 5"
E[2021-01-05|14:22:24.340] enterPrevote: ProposalBlock is invalid       module=consensus height=14176 round=4 err="Wrong Block.Header.AppHash.  Expected 6007DF17B8E4E8ED5D308220BFB806311EB74C118D26FDD370DEB7DEF3FE29FC, got A8753B91B2EE3E391EA0DA87E2FB66F591BDC95F1B5AB901F6BEC4BE357F04B9"
E[2021-01-05|14:22:24.340] Error signing vote                           module=consensus height=14176 round=4 vote="Vote{3:BA9BF4CBA3A4 14176/04/1(Prevote) 000000000000 000000000000 @ 2021-01-05T06:22:24.340473609Z}" err="error signing vote: round regression at height 14176. Got 4, last round 5"
E[2021-01-05|14:22:24.341] Error signing vote                           module=consensus height=14176 round=4 vote="Vote{3:BA9BF4CBA3A4 14176/04/2(Precommit) 000000000000 000000000000 @ 2021-01-05T06:22:24.341957043Z}" err="error signing vote: round regression at height 14176. Got 4, last round 5"
E[2021-01-05|14:22:24.344] Error signing vote                           module=consensus height=14176 round=5 vote="Vote{3:BA9BF4CBA3A4 14176/05/1(Prevote) 6B052D3BFE1F 000000000000 @ 2021-01-05T06:22:24.344715389Z}" err="error signing vote: step regression at height 14176 round 5. Got 2, last step 3"
INFO[0014] totalSupply 400000000000000000               
INFO[0014] curBlkHeight: 14176                          
I[2021-01-05|14:22:36.821] Executed block                               module=state height=14176 validTxs=0 invalidTxs=0
I[2021-01-05|14:22:36.829] Committed state                              module=state height=14176 txs=0 appHash=493171A5684765F9724EBEFCB39355E14A65EF09E756A8E47ED51F50F958F167
INFO[0019] totalSupply 400000000000000000               
INFO[0019] curBlkHeight: 14177                          
I[2021-01-05|14:22:42.221] Executed block                               module=state height=14177 validTxs=0 invalidTxs=0
I[2021-01-05|14:22:42.226] Committed state                              module=state height=14177 txs=0 appHash=CD5F69F62144093A61589933B75285C2F04E0CE4979C22CDA91F8FEF9F1F4C9D
INFO[0024] totalSupply 400000000000000000               
INFO[0024] curBlkHeight: 14178                          
I[2021-01-05|14:22:47.633] Executed block                               module=state height=14178 validTxs=0 invalidTxs=0
I[2021-01-05|14:22:47.640] Committed state                              module=state height=14178 txs=0 appHash=09925B6F79F537F42C20E07D24F5ED796ACD307075717E490B358B9B9482F316
E[2021-01-05|14:22:53.027] Dialing failed                               module=pex addr=7292fe1c7dcf921f2176a9a178610dba7d233ac8@192.168.0.174:26656 err="auth failure: secret conn failed: EOF" attempts=1
INFO[0030] totalSupply 400000000000000000               
INFO[0030] curBlkHeight: 14179                          
I[2021-01-05|14:22:53.042] Executed block                               module=state height=14179 validTxs=0 invalidTxs=0
I[2021-01-05|14:22:53.047] Committed state                              module=state height=14179 txs=0 appHash=5D4085F59A27469D41ED22B78B824B8173AEFE913F42DAF314E720094CACD796

```

**Comment by youngqqcn** [comment]
test case 3:   
A validator node which named Node4, its power was greather than  2/3 , then this validator proposed a invalid block. It caused the other 3 node crashed at invalid block. 

Node1~3
```
ime="2021-01-05T14:42:42+08:00" level=info msg="totalSupply 400000000000000000"
time="2021-01-05T14:42:42+08:00" level=info msg="curBlkHeight: 14377"
I[2021-01-05|14:42:42.124] Executed block                               module=state height=14377 validTxs=0 invalidTxs=0
I[2021-01-05|14:42:42.130] Committed state                              module=state height=14377 txs=0 appHash=FB0D7D432A517220F37F87AEB0E4F723B9490D22AC22991A81407F08964226AF
time="2021-01-05T14:42:47+08:00" level=info msg="totalSupply 400000000000000000"
time="2021-01-05T14:42:47+08:00" level=info msg="curBlkHeight: 14378"
time="2021-01-05T14:42:47+08:00" level=info msg="=== v2.HandleOpenContract  ==="
time="2021-01-05T14:42:47+08:00" level=info msg="blockHeaderTime: 2021-01-05T06:42:41.941737649Z"
I[2021-01-05|14:42:47.053] Executed block                               module=state height=14378 validTxs=1 invalidTxs=0
I[2021-01-05|14:42:47.060] Committed state                              module=state height=14378 txs=1 appHash=458F4598BA59AA0BC73C5E13D6ABFC6BD07962D4C5AD5ADF6843012F1ACC04DE
E[2021-01-05|14:42:52.266] CONSENSUS FAILURE!!!                         module=consensus err="Panicked on a Consensus Failure: +2/3 committed an invalid block: Wrong Block.Header.AppHash.  Expected 458F4598BA59AA0BC73C5E13D6ABFC6BD07962D4C5AD5ADF6843012F1ACC04DE, got E941186EB5BFA4729F29E45DDC43BFBAAC8FF020E920F50D85E704D27D70B8F3" stack="goroutine 204 [running]:\nruntime/debug.Stack(0xc000f62fb0, 0x10e9360, 0xc0009d9880)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc000ab1180, 0x1424848)\n\t/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/state.go:611 +0x57\npanic(0x10e9360, 0xc0009d9880)\n\t/usr/local/go/src/runtime/panic.go:969 +0x1b9\ngithub.com/tendermint/tendermint/libs/common.PanicConsensus(...)\n\t/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/libs/common/errors.go:239\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000ab1180, 0x382b)\n\t/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/state.go:1289 +0xf78\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000ab1180, 0x382b)\n\t/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/state.go:1266 +0x3c8\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addProposalBlockPart(0xc000ab1180, 0xc0030b3f00, 0xc0034ca510, 0x28, 0xed7860101, 0xc0041e1530, 0xc000f63c10)\n\t/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/state.go:1505 +0x4ca\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000ab1180, 0x156b9a0, 0xc0030b3f00, 0xc0034ca510, 0x28)\n\t/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/state.go:685 +0x265\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000ab1180, 0x0)\n\t/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/state.go:642 +0x6f4\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/state.go:334 +0x165\n"
E[2021-01-05|14:43:14.250] Connection failed @ recvRoutine (reading byte) module=p2p peer=7292fe1c7dcf921f2176a9a178610dba7d233ac8@192.168.0.174:38616 conn=MConn{192.168.0.174:38616} err=EOF
E[2021-01-05|14:43:14.250] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.0.174:38616} 7292fe1c7dcf921f2176a9a178610dba7d233ac8 in}" err=EOF

```

Node4 is ok, and continous make new block.

```
[2021-01-05|14:42:31.933] Executed block                               module=state height=14375 validTxs=1 invalidTxs=0
I[2021-01-05|14:42:31.938] Committed state                              module=state height=14375 txs=1 appHash=1CFB2CA2E6765B092EA51976479EEB77D5E1282BAD7292CD3FCD1357A48417D1
INFO[0050] totalSupply 400000000000000000               
INFO[0050] curBlkHeight: 14376                          
I[2021-01-05|14:42:36.940] Executed block                               module=state height=14376 validTxs=0 invalidTxs=0
I[2021-01-05|14:42:36.945] Committed state                              module=state height=14376 txs=0 appHash=6D2437EEC8F6B17D10F9B126698791C31E5DFE8CDB27F317AF6D0FE36B461FA4
INFO[0055] totalSupply 400000000000000000               
INFO[0055] curBlkHeight: 14377                          
I[2021-01-05|14:42:41.951] Executed block                               module=state height=14377 validTxs=0 invalidTxs=0
I[2021-01-05|14:42:41.956] Committed state                              module=state height=14377 txs=0 appHash=FB0D7D432A517220F37F87AEB0E4F723B9490D22AC22991A81407F08964226AF
E[2021-01-05|14:42:46.826] Dialing failed                               module=pex addr=7292fe1c7dcf921f2176a9a178610dba7d233ac8@192.168.0.174:26656 err="auth failure: secret conn failed: EOF" attempts=2
INFO[0060] totalSupply 400000000000000000               
INFO[0060] curBlkHeight: 14378                          
INFO[0060] === v2.HandleOpenContract  ===               
INFO[0060] blockHeaderTime: 2021-01-05T06:42:41.941737649Z 
WARN[0060] !!!!!!!!!!!HACK_TEST__blockHeaderTime: 2021-01-05T06:52:41.941737649Z !!!!!!!!! 
I[2021-01-05|14:42:46.965] Executed block                               module=state height=14378 validTxs=1 invalidTxs=0
I[2021-01-05|14:42:46.971] Committed state                              module=state height=14378 txs=1 appHash=E941186EB5BFA4729F29E45DDC43BFBAAC8FF020E920F50D85E704D27D70B8F3
INFO[0065] totalSupply 400000000000000000               
INFO[0065] curBlkHeight: 14379                          
I[2021-01-05|14:42:51.974] Executed block                               module=state height=14379 validTxs=0 invalidTxs=0
I[2021-01-05|14:42:51.980] Committed state                              module=state height=14379 txs=0 appHash=C60D4FA13C1D4650E118C485603E925D781DD33278C81C8F33E809F7DF255383
INFO[0070] totalSupply 400000000000000000               
INFO[0070] curBlkHeight: 14380                          
I[2021-01-05|14:42:56.980] Executed block                               module=state height=14380 validTxs=0 invalidTxs=0
I[2021-01-05|14:42:56.986] Committed state                              module=state height=14380 txs=0 appHash=1CDC0B0D3F6DCF5E7420E2D115AF274A0CD4ED906E42DEE040FC32525355877D
INFO[0075] totalSupply 400000000000000000               
INFO[0075] curBlkHeight: 14381                          
I[2021-01-05|14:43:01.989] Executed block                               module=state height=14381 validTxs=0 invalidTxs=0
I[2021-01-05|14:43:01.995] Committed state                              module=state height=14381 txs=0 appHash=037CEFC57EDDEE309500687E1E8D19CB3B4E039E8A90D24E4094C346B581C54D

```

In this case , What can we do to recover the chain?


I try to replay bad `hsd` with  good `hsd` and  use `hsd reset --height=14370` to recover chain, but it isn't useful.

```
root@node4 ~]# hsd reset --height=14370
INFO[0000] /---------flag1----------/ true              
currVersion=2
LastBlockHeight=14383
NOTE: This Reset operation will change the application store!
NOTE: Backup(备份,備份,지원,Apoyo,Резервный) your node home directory before proceeding!
Please input reset height again:
14370
Please input absolute path of your backuped node home directory for check it's exists:
/root/.hsd_crash_222
The last block height is 14383, will reset height to 14370.
Are you sure to proceed? (yes/n)
yes
I[2021-01-05|14:46:00.779] The last block height is 14383, loaded store at 14370 module=main 
Reset App state to height 14370 successfully.Then use the `hsd start` to start node.
[root@node4 ~]# 
[root@node4 ~]# hsd start
I[2021-01-05|14:46:05.513] Starting ABCI with Tendermint                module=main 
INFO[0000] /---------flag1----------/ true              
currVersion=2
LastBlockHeight=14370
INFO[0000] totalSupply 400000000000000000               
INFO[0000] curBlkHeight: 14371                          
INFO[0000] totalSupply 400000000000000000               
INFO[0000] curBlkHeight: 14372                          
INFO[0000] blockHeaderTime: 2021-01-05T06:42:11.872587427Z 
INFO[0000] totalSupply 400000000000000000               
INFO[0000] curBlkHeight: 14373                          
INFO[0000] totalSupply 400000000000000000               
INFO[0000] curBlkHeight: 14374                          
INFO[0000] totalSupply 400000000000000000               
INFO[0000] curBlkHeight: 14375                          
INFO[0000] === v2.HandleOpenContract  ===               
INFO[0000] blockHeaderTime: 2021-01-05T06:42:26.907204328Z 
INFO[0000] totalSupply 400000000000000000               
INFO[0000] curBlkHeight: 14376                          
INFO[0000] totalSupply 400000000000000000               
INFO[0000] curBlkHeight: 14377                          
INFO[0000] totalSupply 400000000000000000               
INFO[0000] curBlkHeight: 14378                          
INFO[0000] === v2.HandleOpenContract  ===               
INFO[0000] blockHeaderTime: 2021-01-05T06:42:41.941737649Z 
panic: AppHash mismatch: expected E941186EB5BFA4729F29E45DDC43BFBAAC8FF020E920F50D85E704D27D70B8F3, actual 458F4598BA59AA0BC73C5E13D6ABFC6BD07962D4C5AD5ADF6843012F1ACC04DE

goroutine 1 [running]:
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(0xc000faf6c8, 0xa, 0x0, 0xc000b04686, 0x6, 0xc000b046a0, 0x9, 0x382f, 0x24, 0xc000af04c0, ...)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/replay.go:427 +0x7d7
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000faf6c8, 0xa, 0x0, 0xc000b04686, 0x6, 0xc000b046a0, 0x9, 0x382f, 0x24, 0xc000af04c0, ...)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/replay.go:362 +0xac5
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000faf6c8, 0x1599c00, 0xc0001273b0, 0xc0001dd180, 0x158b080, 0xc000b03a00)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/replay.go:267 +0x5c8
github.com/tendermint/tendermint/node.NewNode(0xc0001dd180, 0x1585c00, 0xc0008b9720, 0xc0001df8c0, 0x156bc20, 0xc000a969c0, 0xc0001dfea0, 0x1424950, 0xc0001dfeb0, 0x158b080, ...)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/node/node.go:266 +0xa52
github.com/orientwalt/htdf/server.startInProcess(0xc000955780, 0x1425308, 0x1d, 0x0, 0x0)
	/data/work/htdf/server/start.go:128 +0x4fb
github.com/orientwalt/htdf/server.StartCmd.func1(0xc0001b0000, 0x1ccf980, 0x0, 0x0, 0x0, 0x0)
	/data/work/htdf/server/start.go:44 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc0001b0000, 0x1ccf980, 0x0, 0x0, 0xc0001b0000, 0x1ccf980)
	/home/yqq/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d4780, 0x12c762f, 0xc00091fef0, 0xade066)
	/home/yqq/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/home/yqq/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000d4780, 0x1425750, 0x12a4d97, 0x9)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/libs/cli/setup.go:89 +0x3c
main.main()
	/data/work/htdf/cmd/hsd/main.go:82 +0x7fd
[root@node4 ~]# 

```
