### ISSUE TITLE
`hsd export` data format  could not be used as new chain genesis data directly

### ISSUE THREAD

**Issue by youngqqcn** [orientwalt/htdf#36]
expected account data format:
```json
"app_state": {                                                 
  "accounts": [                                                
    {                                                          
      "address": "htdf1rg46k2m9fde2d2zg25qdctuxxxzzmj0zpgwevy",
      "coins": [                                               
        {                                                      
          "denom": "satoshi",                                  
          "amount": "3000000000000000"                         
        }                                                      
      ],                                                       
      "sequence_number": "0",                                  
      "account_number": "0",                                   
      "original_vesting": null,                                
      "delegated_free": null,                                  
      "delegated_vesting": null,                               
      "start_time": "0",                                       
      "end_time": "0"                                          
    },                                                         
```

hsd export  `account` format:

```json
"app_state": {
  "accounts": [
    {
      "address": "htdf1rg46k2m9fde2d2zg25qdctuxxxzzmj0zpgwevy",
      "coins": [
        "1999989997000000satoshi"
      ],
      "sequence_number": "2",
      "account_number": "0"
 }
```

panic log:
```
yqq@ubuntu:htdf$ hsd start
I[2021-03-08|16:41:23.869] Starting ABCI with Tendermint                module=main 
INFO[0000] /---------flag1----------/ true              
currVersion=0
LastBlockHeight=0
panic: json: cannot unmarshal string into Go value of type map[string]json.RawMessage

goroutine 1 [running]:
github.com/orientwalt/htdf/app/v0.(*ProtocolV0).InitChainer(0xc000d09800, 0x1571460, 0xc000de0480, 0xc00004a600, 0x10, 0xc0001eecf0, 0x2c0e2562, 0xed7d78ccf, 0x0, 0xc0004db080, ...)
        /data/work/htdf/app/v0/protocol_v0.go:463 +0x769
github.com/orientwalt/htdf/app.(*BaseApp).InitChain(0xc000188380, 0x2c0e2562, 0xed7d78ccf, 0x0, 0xc0004db080, 0x9, 0xc00004a400, 0x1cac810, 0x0, 0x0, ...)
        /data/work/htdf/app/baseapp.go:420 +0x3c2
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000a34960, 0x2c0e2562, 0xed7d78ccf, 0x0, 0xc0004db080, 0x9, 0xc00004a400, 0x1cac810, 0x0, 0x0, ...)
        /home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/abci/client/local_client.go:223 +0xf8
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000b0db40, 0x2c0e2562, 0xed7d78ccf, 0x0, 0xc0004db080, 0x9, 0xc00004a400, 0x1cac810, 0x0, 0x0, ...)
        /home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/proxy/app_conn.go:65 +0x75
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000a496c8, 0xa, 0x0, 0xc0004db3b6, 0x6, 0xc0004db3d0, 0x9, 0x0, 0x0, 0x0, ...)
        /home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/replay.go:309 +0x696
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000a496c8, 0x1580960, 0xc000b08540, 0xc000a0fe00, 0x1571de0, 0xc0001f9940)
        /home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/consensus/replay.go:267 +0x5c8
github.com/tendermint/tendermint/node.NewNode(0xc000a0fe00, 0x156c9a0, 0xc000a16000, 0xc000b0c000, 0x1552c20, 0xc00001f980, 0xc000b0c2b0, 0x140c060, 0xc000b0c2c0, 0x1571de0, ...)
        /home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/node/node.go:266 +0xa52
github.com/orientwalt/htdf/server.startInProcess(0xc00001f340, 0x140ca18, 0x1d, 0x0, 0x0)
        /data/work/htdf/server/start.go:128 +0x4fb
github.com/orientwalt/htdf/server.StartCmd.func1(0xc000aa2a00, 0x1cac810, 0x0, 0x0, 0x0, 0x0)
        /data/work/htdf/server/start.go:44 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc000aa2a00, 0x1cac810, 0x0, 0x0, 0xc000aa2a00, 0x1cac810)
        /home/yqq/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a24780, 0x12af15f, 0xc000d9fef0, 0xada346)
        /home/yqq/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /home/yqq/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000a24780, 0x140ce60, 0x128cbb3, 0x9)
        /home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.90.10/libs/cli/setup.go:89 +0x3c
main.main()
        /data/work/htdf/cmd/hsd/main.go:88 +0x7fd
```

---

`hsd export ` format

```
"stake": {
...
}
```

expected format for genesis data:

```json
staking": {
.....
}
```

**Comment by youngqqcn** [comment]
fixed
