### ISSUE TITLE
leveldb/table: corruption on data-block 

### ISSUE THREAD

**Issue by youngqqcn** [orientwalt/htdf#4]
```
$ ./hsd start
I[2020-10-19|07:07:08.550] Starting ABCI with Tendermint                module=main 
INFO[0000] /---------flag1----------/ true              
currVersion=1
LastBlockHeight=3350897
panic: Panicked on a Crisis: leveldb/table: corruption on data-block (pos=0): checksum mismatch, want=0x0 got=0xdbaf362c [file=134390.ldb]

goroutine 146 [running]:
github.com/tendermint/tendermint/libs/common.PanicCrisis(...)
        /media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/projects/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/libs/common/errors.go:232
github.com/tendermint/tendermint/libs/db.(*GoLevelDB).Set(0xc00014a220, 0xc0040834d0, 0x9, 0x10, 0xc0008ba300, 0x17d, 0x17d)
        /media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/projects/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/libs/db/go_level_db.go:70 +0x157
github.com/tendermint/tendermint/blockchain.(*BlockStore).SaveBlock(0xc001852bd0, 0xc00000cf00, 0xc0010ea550, 0xc003cb9e00)
        /media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/projects/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/blockchain/store.go:160 +0x1d1
github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc000491520)
        /media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/projects/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/blockchain/reactor.go:339 +0x8ee
created by github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
        /media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/projects/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/blockchain/reactor.go:117 +0x84

```

**Comment by youngqqcn** [comment]
it caused by machine crashed hard and corrupted your database, or you have bad sectors on your drive.

this issue is same as these issue in ethereum:
- [leveldb/table: corruption on data-block](https://github.com/ethereum/go-ethereum/issues/2568)
- [corruption on data-block on Ubuntu](https://github.com/ethereum/go-ethereum/issues/14555)
- [Crash - Failed to store last header's hash](https://github.com/ethereum/go-ethereum/issues/16785)

**Comment by youngqqcn** [comment]
To solve issue,  delete all file in ` ~/.hsd/data/`  and resync from 0 block height.  

> NOTE:  DO NOT REMOVE ANY FILE OF  `~/.hscli/`  which contains keystore file!
