### ISSUE TITLE
[htdf2.0] Tendermint LastCommitRound can only be negative for initial height

### ISSUE THREAD

**Issue by youngqqcn** [orientwalt/htdf#78]
- related issue #55 
```
2021-06-25|16:39:59.556] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:39:59.782] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:39:59.782] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:00.009] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:00.009] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
time="2021-06-25T16:40:00+08:00" level=info msg=mint.BeginBlocker
time="2021-06-25T16:40:00+08:00" level=info msg="totalSupply 12000000000000000"
time="2021-06-25T16:40:00+08:00" level=info msg="curBlkHeight: 8000141"
I[2021-06-25|16:40:00.030] Executed block                               module=state height=8000141 validTxs=0 invalidTxs=0
I[2021-06-25|16:40:00.032] Committed state                              module=state height=8000141 txs=0 appHash=4C69FF37731929C61F73A85C200DE3CA992D7D5A035CF93A894BF25D51DE82A5
E[2021-06-25|16:40:00.247] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:00.247] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:00.475] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:00.475] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:00.704] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:00.704] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:00.934] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:00.934] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:01.160] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:01.160] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:01.387] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:01.387] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:01.614] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:01.614] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:01.853] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:01.853] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:02.089] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:02.089] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:02.325] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:02.325] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:02.561] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:02.561] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:02.797] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:02.797] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:03.024] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:03.024] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:03.260] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:03.260] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:03.485] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:03.485] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:03.711] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:03.711] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:03.940] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:03.940] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:04.169] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:04.169] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:04.398] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:04.398] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:04.637] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:04.637] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:04.876] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:04.876] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:05.103] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:05.103] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:05.329] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"
E[2021-06-25|16:40:05.329] Stopping peer for error                      module=p2p peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" err="LastCommitRound can only be negative for initial height 8000000"
time="2021-06-25T16:40:05+08:00" level=info msg=mint.BeginBlocker
time="2021-06-25T16:40:05+08:00" level=info msg="totalSupply 12000000000000000"
time="2021-06-25T16:40:05+08:00" level=info msg="curBlkHeight: 8000142"
I[2021-06-25|16:40:05.354] Executed block                               module=state height=8000142 validTxs=0 invalidTxs=0
I[2021-06-25|16:40:05.356] Committed state                              module=state height=8000142 txs=0 appHash=53A333E9AC0298819BAB2AC1796E220ADA8E6BC32EEC3C000A9BC653C293F8A2
E[2021-06-25|16:40:05.555] Peer sent us invalid msg                     module=consensus peer="Peer{MConn{103.45.110.198:26656} 244a9169761496c3546d92d08446188295d39ff4 out}" msg="[NewRoundStep H:8000129 R:0 S:RoundStepPrevote LCR:-1]" err="LastCommitRound can only be negative for initial height 8000000"

```

**Comment by deep2chain** [comment]
@youngqqcn  what is initial height? I am wondering why LastCommitRound was set as negative value.
- https://github.com/orientwalt/tendermint/blob/htdf2.0/fiture_replaylastblock/consensus/reactor.go#L1468
```go
// ValidateHeight validates the height given the chain's initial height.
func (m *NewRoundStepMessage) ValidateHeight(initialHeight int64) error {
	if m.Height < initialHeight {
		return fmt.Errorf("invalid Height %v (lower than initial height %v)",
			m.Height, initialHeight)
	}
	if m.Height == initialHeight && m.LastCommitRound != -1 {
		return fmt.Errorf("invalid LastCommitRound %v (must be -1 for initial height %v)",
			m.LastCommitRound, initialHeight)
	}
	if m.Height > initialHeight && m.LastCommitRound < 0 {
		return fmt.Errorf("LastCommitRound can only be negative for initial height %v", // nolint
			initialHeight)
	}
	return nil
}
```

**Comment by youngqqcn** [comment]
@deep2chain  

I tested  it on local testnet with 4 validator nodes.  After started and stopped (`pkill hsd` ) chain, when restarting the chain, one of these nodes showed this error msg. 

This error isn't  inevitable, however its occurrence probability is  relatively high.

**Comment by youngqqcn** [comment]
https://github.com/orientwalt/tendermint/blob/7e46f35bc7f5ffc2e856390bdd21af5834793270/consensus/reactor.go#L944-L956
```go
// NewPeerState returns a new PeerState for the given Peer
func NewPeerState(peer p2p.Peer) *PeerState {
	return &PeerState{
		peer:   peer,
		logger: log.NewNopLogger(),
		PRS: cstypes.PeerRoundState{
			Round:              -1,
			ProposalPOLRound:   -1,
			LastCommitRound:    -1,
			CatchupCommitRound: -1,
		},
		Stats: &peerStateStats{},
	}
}

```

**Comment by youngqqcn** [comment]
I debug `hsd`  at node1 


```
Breakpoint 4, github.com/tendermint/tendermint/consensus.(*NewRoundStepMessage).ValidateHeight (
    m=0xc000d15e60, initialHeight=1, ~r1=...)
    at /root/go/pkg/mod/github.com/orientwalt/tendermint@v0.99.5-rc2/consensus/reactor.go:1469
1469			return fmt.Errorf("LastCommitRound can only be negative for initial height %v", // nolint
(gdb) l
1464		if m.Height == initialHeight && m.LastCommitRound != -1 {
1465			return fmt.Errorf("invalid LastCommitRound %v (must be -1 for initial height %v)",
1466				m.LastCommitRound, initialHeight)
1467		}
1468		if m.Height > initialHeight && m.LastCommitRound < 0 {
1469			return fmt.Errorf("LastCommitRound can only be negative for initial height %v", // nolint
1470				initialHeight)
1471		}
1472		return nil
1473	}
(gdb) p m.LastCommitRound 
$5 = -1
(gdb) p m.Height 
$6 = 504
(gdb) 

```

**Comment by youngqqcn** [comment]
I want recover node4 by  `hsd unsafe-reset-all`, but failed to start

```
E[2021-06-30|11:20:02.414] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.0.172:26656} 273464deb370ff92a6024c5ffac2d5a92a4478af out}" err="wrong LastCommit: commit cannot be for nil block"
E[2021-06-30|11:20:03.537] Peer sent us invalid msg                     module=blockchain peer="Peer{MConn{192.168.0.173:26656} d12552880e8b23212a680cb778da1da785e24b79 out}" msg="[bcBlockResponseMessage 1]" err="wrong LastCommit: commit cannot be for nil block"
E[2021-06-30|11:20:03.537] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.0.173:26656} d12552880e8b23212a680cb778da1da785e24b79 out}" err="wrong LastCommit: commit cannot be for nil block"
E[2021-06-30|11:20:05.964] Peer sent us invalid msg                     module=blockchain peer="Peer{MConn{192.168.0.172:26656} 273464deb370ff92a6024c5ffac2d5a92a4478af out}" msg="[bcBlockResponseMessage 1]" err="wrong LastCommit: commit cannot be for nil block"
E[2021-06-30|11:20:05.964] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.0.172:26656} 273464deb370ff92a6024c5ffac2d5a92a4478af out}" err="wrong LastCommit: commit cannot be for nil block"
E[2021-06-30|11:20:06.180] Peer sent us invalid msg                     module=blockchain peer="Peer{MConn{192.168.0.173:26656} d12552880e8b23212a680cb778da1da785e24b79 out}" msg="[bcBlockResponseMessage 1]" err="wrong LastCommit: commit cannot be for nil block"
E[2021-06-30|11:20:06.180] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.0.173:26656} d12552880e8b23212a680cb778da1da785e24b79 out}" err="wrong LastCommit: commit cannot be for nil block"
E[2021-06-30|11:20:07.907] Peer sent us invalid msg                     module=blockchain peer="Peer{MConn{192.168.0.173:26656} d12552880e8b23212a680cb778da1da785e24b79 out}" msg="[bcBlockResponseMessage 1]" err="wrong LastCommit: commit cannot be for nil block"
E[2021-06-30|11:20:07.907] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.0.173:26656} d12552880e8b23212a680cb778da1da785e24b79 out}" err="wrong LastCommit: commit cannot be for nil block"
E[2021-06-30|11:20:09.329] Peer sent us invalid msg                     module=blockchain peer="Peer{MConn{192.168.0.173:26656} d12552880e8b23212a680cb778da1da785e24b79 out}" msg="[bcBlockResponseMessage 1]" err="wrong LastCommit: commit cannot be for nil block"
E[2021-06-30|11:20:09.329] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.0.173:26656} d12552880e8b23212a680cb778da1da785e24b79 out}" err="wrong LastCommit: commit cannot be for nil block"

```

**Comment by youngqqcn** [comment]
> @deep2chain
> 
> I tested it on local testnet with 4 validator nodes. After started and stopped (`pkill hsd` ) chain, when restarting the chain, one of these nodes showed this error msg.
> 
> ~This error isn't inevitable, however its occurrence probability is relatively high.~
> 
> `pkill hsd` caused this error .
> 
> 4 nodes, I `pkill` node4, other nodes still made new blocks with `peer` error msg in log. The node4 didn't make new block any more.

@deep2chain   

I found out a way to  reappear this error  100% probability : 

-  4 validator nodes 
-  Stop one of the nodes
-  Waiting for the other 3 nodes make one or more of new blocks 
-  Restart the stopped node again, 
-  Got ERROR

**Comment by deep2chain** [comment]
@youngqqcn Thanks for your analysis. The problem is being investigated

**Comment by deep2chain** [comment]
```
I[2021-07-05|15:51:20.576] Executed block                               module=state height=8000173 validTxs=0 invalidTxs=0
I[2021-07-05|15:51:20.578] Committed state                              module=state height=8000173 txs=0 appHash=FEFEF8F3FBDEBAE072C93A0A0E2442B907AC4513019350E6D24BBE6FD9D03D4A
INFO[0002] mint.BeginBlocker                            
INFO[0002] totalSupply 6000003151594944                 
INFO[0002] curBlkHeight: 8000174                        
INFO[0002] BlockProvision: 16976549                     
INFO[0002] curAmplitude: 3130664                        
INFO[0002] curCycle: 1176                               
INFO[0002] curLastIndex: 8000000                        
INFO[0002] []                                           
I[2021-07-05|15:51:20.582] Executed block                               module=state height=8000174 validTxs=0 invalidTxs=0
I[2021-07-05|15:51:20.584] Committed state                              module=state height=8000174 txs=0 appHash=C274FD670A3183AADD258BFA5E4EB173582EA8C2571A504BE32498F6BB05A5E5
Height:8000175, Round:0, Step:1, LastCommitRound:-1
panic: nil

goroutine 84 [running]:
github.com/tendermint/tendermint/consensus.makeRoundStepMessage(0xc000ee4428, 0xffffffffffffffff)
	/media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/company/orientwalt/tendermint/consensus/reactor.go:461 +0x2d0
github.com/tendermint/tendermint/consensus.(*Reactor).broadcastNewRoundStepMessage(0xc0001a3380, 0xc000ee4428)
	/media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/company/orientwalt/tendermint/consensus/reactor.go:414 +0x2f
github.com/tendermint/tendermint/consensus.(*Reactor).subscribeToBroadcastEvents.func1(0x136b400, 0xc000ee4428)
	/media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/company/orientwalt/tendermint/consensus/reactor.go:393 +0x45
github.com/tendermint/tendermint/libs/events.(*eventCell).FireEvent(0xc00021ffc0, 0x136b400, 0xc000ee4428)
	/media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/company/orientwalt/tendermint/libs/events/events.go:198 +0x1e5
github.com/tendermint/tendermint/libs/events.(*eventSwitch).FireEvent(0xc0000ad0a0, 0x14586d7, 0xc, 0x136b400, 0xc000ee4428)
	/media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/company/orientwalt/tendermint/libs/events/events.go:158 +0xa7
github.com/tendermint/tendermint/consensus.(*State).newStep(0xc000ee4380)
	/media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/company/orientwalt/tendermint/consensus/state.go:602 +0x1a0
github.com/tendermint/tendermint/consensus.(*State).updateToState(0xc000ee4380, 0xa, 0x0, 0xc000eb5c50, 0x6, 0xc000eb5c60, 0x9, 0x7a1200, 0x7a12ae, 0xc0039be280, ...)
	/media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/company/orientwalt/tendermint/consensus/state.go:592 +0x3a2
github.com/tendermint/tendermint/consensus.(*Reactor).SwitchToConsensus(0xc0001a3380, 0xa, 0x0, 0xc000eb5c50, 0x6, 0xc000eb5c60, 0x9, 0x7a1200, 0x7a12ae, 0xc0039be280, ...)
	/media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/company/orientwalt/tendermint/consensus/reactor.go:107 +0xdb
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00007ae00)
	/media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/company/orientwalt/tendermint/blockchain/v0/reactor.go:276 +0x1189
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	/media/falcon/f99296dd-81fb-497d-aa4a-9d340af6207a/code/go/company/orientwalt/tendermint/blockchain/v0/reactor.go:118 +0x84

```

**Comment by deep2chain** [comment]
@youngqqcn you can checkout this commit: https://github.com/orientwalt/tendermint/commit/d4923e75051c86d01a42c7f2c86438043e3781d6

**Comment by youngqqcn** [comment]
@deep2chain  

Latest commit  https://github.com/orientwalt/tendermint/commit/8dbcd1d016b9d7cb19950f33cfb9144bbc20e4b8  , everything is ok when the `initial_height` be set as `1`. 

But when change `initial_height` to larger number , such as `8000000` , the node which was last one to run `hsd start` didn't make any blocks.

**Comment by youngqqcn** [comment]
log:
```
INFO[0000] bondValidator===================== Pool:
  Loose Tokens:  6000000100000000
  Bonded Tokens: 300000000
  Token Supply:  6000000400000000
  Bonded Ratio:  0.000000049999996666 
E[2021-07-06|11:59:21.951] Can't add peer's address to addrbook         module=p2p err="Cannot add non-routable address 32efe9b2d5ba271dc851fce6082520f242785374@192.168.0.171:26656"
E[2021-07-06|11:59:21.951] Can't add peer's address to addrbook         module=p2p err="Cannot add non-routable address c28e3b6905ff3f92564be9d7e5d1d66b6d81cb7f@192.168.0.172:26656"
E[2021-07-06|11:59:21.951] Can't add peer's address to addrbook         module=p2p err="Cannot add non-routable address 200802b26d4e067ed27d4531c514edd55e978e12@192.168.0.173:26656"
E[2021-07-06|11:59:28.117] ==========>ApplyNewRoundStepMessage CompareHRS() < 0 module=consensus 
E[2021-07-06|11:59:28.117] ==========>ApplyNewRoundStepMessage CompareHRS() < 0 module=consensus 
E[2021-07-06|11:59:28.219] ==========>ApplyNewRoundStepMessage CompareHRS() < 0 module=consensus 
```



```go
switch chID {
	case StateChannel:
		switch msg := msg.(type) {
		case *NewRoundStepMessage:
			// conR.conS.mtx.Lock()
			// initialHeight := conR.conS.state.InitialHeight
			// conR.conS.mtx.Unlock()
			// if err = msg.ValidateHeight(initialHeight); err != nil {
			// 	conR.Logger.Error("Peer sent us invalid msg", "peer", src, "msg", msg, "err", err)
			// 	conR.Switch.StopPeerForError(src, err)
			// 	return
			// }
			ps.ApplyNewRoundStepMessage(msg)
```


```go

// ApplyNewRoundStepMessage updates the peer state for the new round.
func (ps *PeerState) ApplyNewRoundStepMessage(msg *NewRoundStepMessage) {
	ps.mtx.Lock()
	defer ps.mtx.Unlock()

	// Ignore duplicates or decreases
	if CompareHRS(msg.Height, msg.Round, msg.Step, ps.PRS.Height, ps.PRS.Round, ps.PRS.Step) <= 0 {
		return
	}
    ///....
}

```

**Comment by youngqqcn** [comment]
https://github.com/tendermint/tendermint/pull/5191#pullrequestreview-578775506

**Comment by deep2chain** [comment]
- height==1
```
Starting	Peer	service	module=p2p	peer=2a01e87843a93537eb8c711e3627c277171fb10a@192.168.0.172:56180	impl="Peer{MConn{192.168.0.172:56180}	2a01e87843a93537eb8c711e3627c277171fb10a	in}"
Starting	MConnection	service	module=p2p	peer=2a01e87843a93537eb8c711e3627c277171fb10a@192.168.0.172:56180	impl=MConn{192.168.0.172:56180}
Added	peer	module=p2p	peer="Peer{MConn{192.168.0.172:56180}	2a01e87843a93537eb8c711e3627c277171fb10a	in}"
Starting	Peer	service	module=p2p	peer=59665ff52b85b29128a1f2e2ce8181dbad0157da@192.168.0.171:58286	impl="Peer{MConn{192.168.0.171:58286}	59665ff52b85b29128a1f2e2ce8181dbad0157da	in}"
Starting	MConnection	service	module=p2p	peer=59665ff52b85b29128a1f2e2ce8181dbad0157da@192.168.0.171:58286	impl=MConn{192.168.0.171:58286}
Added	peer	module=p2p	peer="Peer{MConn{192.168.0.171:58286}	59665ff52b85b29128a1f2e2ce8181dbad0157da	in}"
```
- height != 1
```
Starting	Peer	service	module=p2p	peer=d32a0a306fe2f8a95966615402670cdb3dc7c20d@192.168.0.171:58312	impl="Peer{MConn{192.168.0.171:58312}	d32a0a306fe2f8a95966615402670cdb3dc7c20d	in}"
Starting	MConnection	service	module=p2p	peer=d32a0a306fe2f8a95966615402670cdb3dc7c20d@192.168.0.171:58312	impl=MConn{192.168.0.171:58312}
Added	peer	module=p2p	peer="Peer{MConn{192.168.0.171:58312}	d32a0a306fe2f8a95966615402670cdb3dc7c20d	in}"
Dialing	peer	module=p2p	address=a54a49768a8be6a23bd4fbd8d52d2e046039110c@192.168.0.173:26656
Starting	Peer	service	module=p2p	peer=a54a49768a8be6a23bd4fbd8d52d2e046039110c@192.168.0.173:26656	impl="Peer{MConn{192.168.0.173:26656}	a54a49768a8be6a23bd4fbd8d52d2e046039110c	out}"
Starting	MConnection	service	module=p2p	peer=a54a49768a8be6a23bd4fbd8d52d2e046039110c@192.168.0.173:26656	impl=MConn{192.168.0.173:26656}
Added	peer	module=p2p	peer="Peer{MConn{192.168.0.173:26656}	a54a49768a8be6a23bd4fbd8d52d2e046039110c	out}"
Dialing	peer	module=p2p	address=a722de0f006824988b77148d15f65006ea11fd76@192.168.0.172:26656
Starting	Peer	service	module=p2p	peer=a722de0f006824988b77148d15f65006ea11fd76@192.168.0.172:26656	impl="Peer{MConn{192.168.0.172:26656}	a722de0f006824988b77148d15f65006ea11fd76	out}"
Starting	MConnection	service	module=p2p	peer=a722de0f006824988b77148d15f65006ea11fd76@192.168.0.172:26656	impl=MConn{192.168.0.172:26656}
Added	peer	module=p2p	peer="Peer{MConn{192.168.0.172:26656}	a722de0f006824988b77148d15f65006ea11fd76	out}"
```
