### ISSUE TITLE
[htdf2.0] panic: calculated final stake for delegator htdf1x9cqqpzlk08dgwtkfqxusqrx7zstdnrwm74tmf greater than current stake

### ISSUE THREAD

**Issue by youngqqcn** [orientwalt/htdf#84]
```
panic: calculated final stake for delegator htdf1x9cqqpzlk08dgwtkfqxusqrx7zstdnrwm74tmf greater than current stake
	final stake:	1000000000.000000000000000000
	current stake:	990000003.693902415493644113

goroutine 1 [running]:
github.com/orientwalt/htdf/x/distribution/keeper.Keeper.calculateDelegationRewards(0x16f1f88, 0xc000173970, 0xc00012b180, 0xc00012b180, 0x16f1f88, 0xc0001739c0, 0x16f1fd8, 0xc0001739d0, 0xc000e2c7b0, 0x5, ...)
	/data2/work/htdf/x/distribution/keeper/delegation.go:106 +0x7a5
github.com/orientwalt/htdf/x/distribution/keeper.Keeper.withdrawDelegationRewards(0x16f1f88, 0xc000173970, 0xc00012b180, 0xc00012b180, 0x16f1f88, 0xc0001739c0, 0x16f1fd8, 0xc0001739d0, 0xc000e2c7b0, 0x5, ...)
	/data2/work/htdf/x/distribution/keeper/delegation.go:126 +0x365
github.com/orientwalt/htdf/x/distribution/keeper.Keeper.WithdrawDelegationRewards(0x16f1f88, 0xc000173970, 0xc00012b180, 0xc00012b180, 0x16f1f88, 0xc0001739c0, 0x16f1fd8, 0xc0001739d0, 0xc000e2c7b0, 0x5, ...)
	/data2/work/htdf/x/distribution/keeper/keeper.go:65 +0x228
github.com/orientwalt/htdf/x/distribution/keeper.CanWithdrawInvariant.func1.1(0x0, 0x1712cf8, 0xc00bdc76c0, 0xc00bdc76c0)
	/data2/work/htdf/x/distribution/keeper/invariants.go:84 +0x6c7
github.com/orientwalt/htdf/x/staking/keeper.Keeper.IterateValidators(0x16f1f88, 0xc000173940, 0x16f1fd8, 0xc000173950, 0xc00012b180, 0x7ff5b8f97cb8, 0xc00000d2c0, 0x170e468, 0xc001306640, 0xc00012b180, ...)
	/data2/work/htdf/x/staking/keeper/alias_functions.go:21 +0x25d
github.com/orientwalt/htdf/x/distribution/keeper.CanWithdrawInvariant.func1(0x17000d8, 0xc000e0a330, 0xc000376180, 0x11, 0x0, 0x0)
	/data2/work/htdf/x/distribution/keeper/invariants.go:78 +0x386
github.com/orientwalt/htdf/app/v0.(*ProtocolV0).assertRuntimeInvariants(0xc000e25800, 0x17000d8, 0xc000e0a330, 0xc000376180, 0x11)
	/data2/work/htdf/app/v0/invariants.go:14 +0x3e2
github.com/orientwalt/htdf/app/v0.(*ProtocolV0).InitChainer(0xc000e25800, 0x17000d8, 0xc000e0a330, 0xc000376180, 0x11, 0xc000172230, 0x154ed655, 0xed5ec44d5, 0x0, 0xc000cba9e0, ...)
	/data2/work/htdf/app/v0/protocol_v0.go:545 +0x4ce
github.com/orientwalt/htdf/app.(*BaseApp).InitChain(0xc0000e6dc0, 0x154ed655, 0xed5ec44d5, 0x0, 0xc000cba9e0, 0x9, 0xc0003425c0, 0xc00031e900, 0x13, 0x13, ...)
	/data2/work/htdf/app/abci.go:84 +0x556
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0013647e0, 0x154ed655, 0xed5ec44d5, 0x0, 0xc000cba9e0, 0x9, 0xc0003425c0, 0xc00031e900, 0x13, 0x13, ...)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.99.5/abci/client/local_client.go:223 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000051980, 0x154ed655, 0xed5ec44d5, 0x0, 0xc000cba9e0, 0x9, 0xc0003425c0, 0xc00031e900, 0x13, 0x13, ...)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.99.5/proxy/app_conn.go:65 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0000c2fb0, 0xa, 0x0, 0x1401eb2, 0x6, 0xc000cba9e0, 0x9, 0x786fc7, 0x0, 0x0, ...)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.99.5/consensus/replay.go:333 +0x6d5
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0000c2fb0, 0x1710560, 0xc000e5c000, 0xc0001f6140, 0x203000, 0x203000)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.99.5/consensus/replay.go:279 +0x4cc
github.com/tendermint/tendermint/node.doHandshake(0xc0001f6140, 0x170faf8, 0xc0000a0230, 0xa, 0x0, 0x1401eb2, 0x6, 0xc000cba9e0, 0x9, 0x786fc7, ...)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.99.5/node/node.go:288 +0x1a7
github.com/tendermint/tendermint/node.NewNode(0xc0001f6140, 0x16fb588, 0xc000338820, 0xc0013105d0, 0x16e1560, 0xc000e70be8, 0xc001310790, 0x1592ca8, 0xc0013107a0, 0x17008f0, ...)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.99.5/node/node.go:611 +0x3c5
github.com/orientwalt/htdf/server.startInProcess(0xc00013ceb8, 0x1594400, 0x0, 0x0)
	/data2/work/htdf/server/start.go:102 +0x55d
github.com/orientwalt/htdf/server.StartCmd.func1(0xc00012c840, 0x1ef1088, 0x0, 0x0, 0x0, 0x0)
	/data2/work/htdf/server/start.go:54 +0xa5
github.com/spf13/cobra.(*Command).execute(0xc00012c840, 0x1ef1088, 0x0, 0x0, 0xc00012c840, 0x1ef1088)
	/home/yqq/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000fcb00, 0xc0002b5e00, 0x142bef0, 0xc00020fef0)
	/home/yqq/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/yqq/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000fcb00, 0x1594840, 0x1406728, 0x9)
	/home/yqq/go/pkg/mod/github.com/orientwalt/tendermint@v0.99.5/libs/cli/setup.go:89 +0x3c
main.main()
	/data2/work/htdf/cmd/hsd/main.go:81 +0x797

```

**Comment by youngqqcn** [comment]
[issue84.tar.gz](https://github.com/orientwalt/htdf/files/6960735/issue84.tar.gz)

**Comment by youngqqcn** [comment]
```go

// calculate the total rewards accrued by a delegation
func (k Keeper) calculateDelegationRewards(ctx sdk.Context, val sdk.Validator, del sdk.Delegation, endingPeriod uint64) (rewards sdk.DecCoins) {
	// fetch starting info for delegation
	startingInfo := k.GetDelegatorStartingInfo(ctx, del.GetValidatorAddr(), del.GetDelegatorAddr())

	newHeight :=  uint64(ctx.BlockHeight())
	if 0 == newHeight {
		newHeight = uint64(7892935)   // 7892935  is initial_height in genesis.json
	}

	fmt.Printf("ctx.BlockHeight() = %d\n", ctx.BlockHeight())
	if startingInfo.Height == uint64(ctx.BlockHeight()) {
		// started this height, no rewards yet
		return
	}

	startingPeriod := startingInfo.PreviousPeriod
	stake := startingInfo.Stake

	// Iterate through slashes and withdraw with calculated staking for
	// distribution periods. These period offsets are dependent on *when* slashes
	// happen - namely, in BeginBlock, after rewards are allocated...
	// Slashes which happened in the first block would have been before this
	// delegation existed, UNLESS they were slashes of a redelegation to this
	// validator which was itself slashed (from a fault committed by the
	// redelegation source validator) earlier in the same BeginBlock.
	startingHeight := startingInfo.Height
	// Slashes this block happened after reward allocation, but we have to account
	// for them for the stake sanity check below.
	// endingHeight := uint64(ctx.BlockHeight())
	endingHeight := newHeight //uint64(ctx.BlockHeight())
	if endingHeight > startingHeight {
		k.IterateValidatorSlashEventsBetween(ctx, del.GetValidatorAddr(), startingHeight, endingHeight,
			func(height uint64, event types.ValidatorSlashEvent) (stop bool) {
				endingPeriod := event.ValidatorPeriod
				if endingPeriod > startingPeriod {
					rewards = rewards.Add(k.calculateDelegationRewardsBetween(ctx, val, startingPeriod, endingPeriod, stake))

					// Note: It is necessary to truncate so we don't allow withdrawing
					// more rewards than owed.
					stake = stake.MulTruncate(sdk.OneDec().Sub(event.Fraction))
					startingPeriod = endingPeriod
				}
				return false
			},
		)
	}

	// A total stake sanity check; Recalculated final stake should be less than or
	// equal to current stake here. We cannot use Equals because stake is truncated
	// when multiplied by slash fractions (see above). We could only use equals if
	// we had arbitrary-precision rationals.
	currentStake := val.TokensFromShares(del.GetShares())
	if stake.GT(currentStake) {
		// account for rounding errors due to stake being multiplied by slash fractions
		currentStakeRoundUp := val.TokensFromSharesRoundUp(del.GetShares())
		if stake.Equal(currentStakeRoundUp) {
			stake = currentStake
		} else {
			panic(fmt.Sprintf("calculated final stake for delegator %s greater than current stake"+
				"\n\tfinal stake:\t%s"+
				"\n\tcurrent stake:\t%s",
				del.GetDelegatorAddr(), stake, currentStake))
		}
	}

	// calculate rewards for final period
	rewards = rewards.Add(k.calculateDelegationRewardsBetween(ctx, val, startingPeriod, endingPeriod, stake))
	return rewards
}

```

**Comment by youngqqcn** [comment]
- [Chain crashed with consensus failure, about 8 hrs after a hard fork. Delegator staking error ](https://github.com/cosmos/cosmos-sdk/issues/7506 )

- [mechanism rounding fix](https://github.com/cosmos/cosmos-sdk/pull/3788)

**Comment by youngqqcn** [comment]
https://github.com/cosmos/cosmos-sdk/pull/4389/files#diff-1fba04fbe59b301da9da81cb18aa5b84f54840f2f4c396030e004c97f5e17ee9


```go
	// we had arbitrary-precision rationals.
	currentStake := val.TokensFromShares(del.GetShares())
	if stake.GT(currentStake) {

		// Account for rounding inconsistencies between:
		//     currentStake: calculated as in staking with a single computation
		//     stake:        calculated as an accumulation of stake
		//                   calculations across validator's distribution periods
		// These inconsistencies are due to differing order of operations which
		// will inevitably have  different accumulated rounding and may lead to
		// the smallest decimal place being one greater in stake than
		// currentStake. When we calculated slashing by period, even if we
		// round down for each slash fraction, it's possible due to how much is
		// being rounded that we slash less when slashing by period instead of
		// for when we slash without periods. In other words, the single slash,
		// and the slashing by period could both be rounding down but the
		// slashing by period is simply rounding down less, thus making stake >
		// currentStake
		//
		// A small amount of this error is tolerated and corrected for,
		// however any greater amount should be considered a breach in expected
		// behaviour.
		if stake.Equal(currentStake.Add(sdk.SmallestDec().MulInt64(3))) {
			stake = currentStake
		} else {
			panic(fmt.Sprintf("calculated final stake for delegator %s greater than current stake"+
```

**Comment by deep2chain** [comment]
@youngqqcn  ready for testing. commit: ff7d712499e19fc86d733c68620929213a2a8487

**Comment by deep2chain** [comment]
```json
      {
        "address": "htdf1x9cqqpzlk08dgwtkfqxusqrx7zstdnrwm74tmf",
        "coins": [
          {
            "denom": "satoshi",
            "amount": "178897101"
          }
        ],
        "sequence_number": "28",
        "account_number": "22160",
        "original_vesting": [],
        "delegated_free": [],
        "delegated_vesting": [],
        "start_time": "0",
        "end_time": "0"
      },
...
      "delegations": [
        {
          "delegator_address": "htdf1x9cqqpzlk08dgwtkfqxusqrx7zstdnrwm74tmf",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "1000000000.000000000000000000",
          "status": false
        },
...
      "delegator_starting_infos": [
        {
          "delegator_address": "htdf1x9cqqpzlk08dgwtkfqxusqrx7zstdnrwm74tmf",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "6",
            "stake": "1000000000.000000000000000000",
            "height": "345995"
          }
        },

```
- shares
```
        {
          "delegator_address": "htdf1qj332te9ypkmyh2p0kfgf0l32apkh8jsrlp27r",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "253850605.113447897470606825",
          "status": false
        },
        {
          "delegator_address": "htdf1q7lmlh2qjnsjkefpz38krkmzsgl23zwc3ky2mj",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "100000000.000000000000000000",
          "status": false
        },
        {
          "delegator_address": "htdf1x9cqqpzlk08dgwtkfqxusqrx7zstdnrwm74tmf",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "1000000000.000000000000000000",
          "status": false
        },
        {
          "delegator_address": "htdf182fewnuw3w5338xc3afasfnyluvqzkvjn5cdr4",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "3356432209.698824198387465677",
          "status": false
        },
        {
          "delegator_address": "htdf18k48s84eh3afu6qhecq3u0uytjh2fyt4f2jch4",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "320699232641.802502789977646598",
          "status": false
        },
        {
          "delegator_address": "htdf18a6g5u5msn04l87kdk06cn97qjumgemu2phxwd",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "15602446281682.915143920862353824",
          "status": false
        },
        {
          "delegator_address": "htdf1f25gnl2cqcefhl77ng49sjve6djpdg63mztyrt",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "154300000000.000000000000000000",
          "status": false
        },
        {
          "delegator_address": "htdf1vyu75kks5lza00jrl0pntwny4u6wlfns7q6xw3",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "19191919493427.368608003569977418",
          "status": true
        },
        {
          "delegator_address": "htdf1wf4k0az06jgyd5p67252z2cc8vwu2gwdqsed0p",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "100000000.000000000000000000",
          "status": false
        },
        {
          "delegator_address": "htdf10gha88x07lxlj3kup0xznp9ma6wkv9957a6fds",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "10097000000.000000000000000000",
          "status": false
        },
        {
          "delegator_address": "htdf13yya5ets3rnm7dj4tr0m2a7u83ntrr8csky93n",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "200000000.000000000000000000",
          "status": false
        },
        {
          "delegator_address": "htdf1nxsl576v08an9tj6c223n0lmnnxjpqwx8sspex",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "100000000.000000000000000000",
          "status": false
        },
        {
          "delegator_address": "htdf1ng8vzwf3uava4kvy0u58ek944zkfkusg8ldktv",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "440000000.000000000000000000",
          "status": false
        },
        {
          "delegator_address": "htdf16kuej5n0jp0jh9g6eclfcplsunumshkf4nsc7y",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "100000000.000000000000000000",
          "status": false
        },
        {
          "delegator_address": "htdf1lgcjedqvkfuf7h0zrkgj94fvu737pfe6s52g3n",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "shares": "177497596610.454683338003506547",
          "status": false
        },

```
- starting_info.stake
```
      "delegator_starting_infos": [
        {
          "delegator_address": "htdf1qj332te9ypkmyh2p0kfgf0l32apkh8jsrlp27r",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "64",
            "stake": "251312099.999999999999999999",
            "height": "4919975"
          }
        },
        {
          "delegator_address": "htdf1q7lmlh2qjnsjkefpz38krkmzsgl23zwc3ky2mj",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "61",
            "stake": "99000000.369385206344117041",
            "height": "4587043"
          }
        },
        {
          "delegator_address": "htdf1x9cqqpzlk08dgwtkfqxusqrx7zstdnrwm74tmf",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "6",
            "stake": "1000000000.000000000000000000",
            "height": "345995"
          }
        },
        {
          "delegator_address": "htdf182fewnuw3w5338xc3afasfnyluvqzkvjn5cdr4",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "65",
            "stake": "3322867899.999999999999999999",
            "height": "4920300"
          }
        },
        {
          "delegator_address": "htdf18k48s84eh3afu6qhecq3u0uytjh2fyt4f2jch4",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "62",
            "stake": "317492241499.999999999999999999",
            "height": "4705756"
          }
        },
        {
          "delegator_address": "htdf18a6g5u5msn04l87kdk06cn97qjumgemu2phxwd",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "69",
            "stake": "15446421876499.999999999999999999",
            "height": "5548937"
          }
        },
        {
          "delegator_address": "htdf1f25gnl2cqcefhl77ng49sjve6djpdg63mztyrt",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "10",
            "stake": "154300000000.000000000000000000",
            "height": "464559"
          }
        },
        {
          "delegator_address": "htdf1vyu75kks5lza00jrl0pntwny4u6wlfns7q6xw3",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "68",
            "stake": "19000000369385.206344117041918944",
            "height": "4926437"
          }
        },
        {
          "delegator_address": "htdf1wf4k0az06jgyd5p67252z2cc8vwu2gwdqsed0p",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "8",
            "stake": "100000000.000000000000000000",
            "height": "386587"
          }
        },
        {
          "delegator_address": "htdf10gha88x07lxlj3kup0xznp9ma6wkv9957a6fds",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "16",
            "stake": "10097000000.000000000000000000",
            "height": "770143"
          }
        },
        {
          "delegator_address": "htdf13yya5ets3rnm7dj4tr0m2a7u83ntrr8csky93n",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "9",
            "stake": "200000000.000000000000000000",
            "height": "389188"
          }
        },
        {
          "delegator_address": "htdf1nxsl576v08an9tj6c223n0lmnnxjpqwx8sspex",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "7",
            "stake": "100000000.000000000000000000",
            "height": "359825"
          }
        },
        {
          "delegator_address": "htdf1ng8vzwf3uava4kvy0u58ek944zkfkusg8ldktv",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "17",
            "stake": "440000000.000000000000000000",
            "height": "842279"
          }
        },
        {
          "delegator_address": "htdf16kuej5n0jp0jh9g6eclfcplsunumshkf4nsc7y",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "15",
            "stake": "100000000.000000000000000000",
            "height": "585836"
          }
        },
        {
          "delegator_address": "htdf1lgcjedqvkfuf7h0zrkgj94fvu737pfe6s52g3n",
          "validator_address": "htdfvaloper1q7lmlh2qjnsjkefpz38krkmzsgl23zwcm0unve",
          "starting_info": {
            "previous_period": "66",
            "stake": "175722621299.999999999999999999",
            "height": "4925954"
```

**Comment by youngqqcn** [comment]
https://github.com/cosmos/cosmos-sdk/pull/4389

```go
	// A total stake sanity check; Recalculated final stake should be less than or
	// equal to current stake here. We cannot use Equals because stake is truncated
	// when multiplied by slash fractions (see above). We could only use equals if
	// we had arbitrary-precision rationals.
	currentStake := val.TokensFromShares(del.GetShares())

	if stake.GT(currentStake) {
		// AccountI for rounding inconsistencies between:
		//
		//     currentStake: calculated as in staking with a single computation
		//     stake:        calculated as an accumulation of stake
		//                   calculations across validator's distribution periods
		//
		// These inconsistencies are due to differing order of operations which
		// will inevitably have different accumulated rounding and may lead to
		// the smallest decimal place being one greater in stake than
		// currentStake. When we calculated slashing by period, even if we
		// round down for each slash fraction, it's possible due to how much is
		// being rounded that we slash less when slashing by period instead of
		// for when we slash without periods. In other words, the single slash,
		// and the slashing by period could both be rounding down but the
		// slashing by period is simply rounding down less, thus making stake >
		// currentStake
		//
		// A small amount of this error is tolerated and corrected for,
		// however any greater amount should be considered a breach in expected
		// behaviour.
		marginOfErr := sdk.SmallestDec().MulInt64(3)
		if stake.LTE(currentStake.Add(marginOfErr)) {
			stake = currentStake
		} else {
			panic(fmt.Sprintf("calculated final stake for delegator %s greater than current stake"+
				"\n\tfinal stake:\t%s"+
				"\n\tcurrent stake:\t%s",
				del.GetDelegatorAddr(), stake, currentStake))
		}
	}
```

**Comment by youngqqcn** [comment]
As mainnet has been upgraded to v2.0.1 at 2021.08.17 , up to now everything is ok , so I close this issue now.
